baseURL = 'https://example.org/'
languageCode = 'en-us'
title = 'JP Ferguson dot net'
theme = 'ananke'
author = "JP Ferguson"

[markup]
  defaultMarkdownHandler = 'goldmark'
  [markup.goldmark]
    [markup.goldmark.extensions]
      [markup.goldmark.extensions.passthrough]
        enable = true
        [markup.goldmark.extensions.passthrough.delimiters]
          block = [['$$', '$$']]
          inline = [['$', '$']]
[params]
  math = true
  featured_image = '/content/weird_head.jpg'

  # list items
  datesinlist = true

  # footer items
  nextprev = true
  showrss = true
  